//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDBConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.MemberShips = new HashSet<MemberShip>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int GroupId { get; set; }
    
        public virtual ICollection<MemberShip> MemberShips { get; set; }
    }
}
